// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SWGAU.Models;

#nullable disable

namespace SWGAU.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SWGAU.Models.Modelos.Abono", b =>
                {
                    b.Property<int>("AbonoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AbonoId"));

                    b.Property<decimal>("CantidadAbono")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("FechaAbono")
                        .HasColumnType("datetime2");

                    b.Property<string>("FrecuenciaAbono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreAbono")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PlantaId")
                        .HasColumnType("int");

                    b.Property<string>("TipoAbono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AbonoId");

                    b.HasIndex("PlantaId");

                    b.ToTable("Abono", (string)null);
                });

            modelBuilder.Entity("SWGAU.Models.Modelos.Irrigacion", b =>
                {
                    b.Property<int>("IrrigacionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IrrigacionId"));

                    b.Property<decimal>("CantidadAgua")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DuracionRiego")
                        .HasColumnType("decimal(6,2)");

                    b.Property<DateTime>("FechaRiego")
                        .HasColumnType("datetime2");

                    b.Property<string>("FrecuenciaRiego")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MetodoRiego")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PlantaId")
                        .HasColumnType("int");

                    b.HasKey("IrrigacionId");

                    b.HasIndex("PlantaId");

                    b.ToTable("Irrigacion", (string)null);
                });

            modelBuilder.Entity("SWGAU.Models.Modelos.Planta", b =>
                {
                    b.Property<int>("PlantaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlantaId"));

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaSiembra")
                        .HasColumnType("datetime2");

                    b.Property<string>("MetodoSiembra")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NombreCientifico")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NombrePlanta")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoPlanta")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("PlantaId");

                    b.ToTable("Planta", (string)null);
                });

            modelBuilder.Entity("SWGAU.Models.Modelos.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsuarioId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("ContrasenaHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CorreoElectronico")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UsuarioId");

                    b.HasIndex("NombreUsuario")
                        .IsUnique();

                    b.ToTable("Usuario", (string)null);
                });

            modelBuilder.Entity("SWGAU.Models.Modelos.Abono", b =>
                {
                    b.HasOne("SWGAU.Models.Modelos.Planta", "Planta")
                        .WithMany("Abonos")
                        .HasForeignKey("PlantaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Planta");
                });

            modelBuilder.Entity("SWGAU.Models.Modelos.Irrigacion", b =>
                {
                    b.HasOne("SWGAU.Models.Modelos.Planta", "Planta")
                        .WithMany("Irrigaciones")
                        .HasForeignKey("PlantaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Planta");
                });

            modelBuilder.Entity("SWGAU.Models.Modelos.Planta", b =>
                {
                    b.Navigation("Abonos");

                    b.Navigation("Irrigaciones");
                });
#pragma warning restore 612, 618
        }
    }
}
